package http;

public enum Endpoint {
    GET_TASKS,
    GET_TASKS_ID,
    POST_TASKS,
    DELETE_TASKS,
    DELETE_TASKS_ID,
    GET_EPICS,
    GET_EPICS_ID,
    GET_EPICS_ID_SUBTASKS,
    POST_EPICS,
    DELETE_EPICS_ID,
    DELETE_EPICS,
    GET_SUBTASKS,
    GET_SUBTASKS_ID,
    POST_SUBTASKS,
    DELETE_SUBTASKS,
    DELETE_SUBTASKS_ID,
    UNKNOWN
}
